spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-batch-import?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: m123
    driver-class-name: com.mysql.jdbc.Driver
  batch:
      job:
        enabled: false
      initialize-schema: always
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
